[package]
name = "rovhost-gtk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.3.1"
relm4 = "0.4.0-beta.2"
relm4-components = "0.4.0-beta.2"
relm4-macros = "0.4.0-beta.2"
opencv = "0.60"
fragile = "1.0.0"
gstreamer = "0.17.4"
gstreamer-rtsp = "0.17.0"
gstreamer-app = "0.17.0"
gstreamer-video = "0.17.0"
glib = "0.14.8"
glib-macros = "0.14.1"
strum = "0.23.0"
strum_macros = "0.23.1"
dirs = "4.0.0"
tracker = "0.1.1"
rand = "0.8.4"
derivative = "2.0.2"

[dependencies.adw]
package = "libadwaita"
version = "0.1.0-alpha-6"