[package]
name = "rovhost-gtk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
relm4 = "0.4.1"
relm4-components = "0.4.0"
relm4-macros = "0.4.1"
opencv = "0.62.0"
fragile = "1.0.0"
gstreamer = "0.18.0"
gstreamer-rtsp = "0.18.0"
gstreamer-app = "0.18.0"
gstreamer-video = "0.18.0"
glib = "0.15.2"
glib-macros = "0.15.1"
strum = "0.23.0"
strum_macros = "0.23.1"
dirs = "4.0.0"
tracker = "0.1.1"
rand = "0.8.4"
derivative = "2.0.2"
sdl2 = "0.35.1"
sdl2-sys = "0.35.1"
lazy_static = "1.4.0"
pangocairo = "0.15.1"
once_cell = "1.9.0"

[dependencies.adw]
package = "libadwaita"
version = "0.1.0"

[dependencies.gtk]
package = "gtk4"
version = "0.4.1"
features = ["v4_4"]